### PR TITLE
set default reference allele for insertion

### PR DESCRIPTION
**Pull request by sarahhunt**
Also update master

### CODE REVIEW

**Comment by nerdstrike** [comment]
Is this trivially testable? Regression testing and all that.

**Comment by magaliruffier** [comment]
@sarahhunt is there a way of testing this simply or should be pull this in as it is?

**Comment by avullo** [comment]
@sarahhunt sorry to bother again, can you please reply to Mag?

thanks

**Comment by lairdm** [comment]
I was hoping to branch today or Monday, are we pulling this in before the branch? Are we able to add a test? Thanks.

**Comment by sarahhunt** [comment]
@lairdm - after e!90 was released, a problem was reported and this change was quickly added to branch to fix it. It will need to go into master. I had hoped to find the time to add a test but have not done so.

**Comment by lairdm** [comment]
Fair enough. I'll merge it now so I can branch, but scout's honour a test is forthcoming before e92? :)

**Pull request merged**
