### PR TITLE
avoid setting plugins key to undef

### PR DESCRIPTION
**Pull request by willmclaren**

### CODE REVIEW

**Comment by lairdm** [comment]
I assume this a post-release patch for 87?

**Comment by willmclaren** [comment]
Yes. It's a safer fix than the one suggested in this (closed) PR:

https://github.com/Ensembl/ensembl-vep/pull/2

**Comment by lairdm** [comment]
Alright, looks good to me, I'll wait for a second member of Core to do the merge. Thanks.

**Comment by magaliruffier** [comment]
why does it need to go onto the release branch?

**Comment by willmclaren** [comment]
@Zhicheng-Liu reported an issue for the EG REST server, so I assume it is still a problem for them?

**Comment by Zhicheng-Liu** [comment]
@magaliruffier it is breaking EG REST server. We don't have plugins configured for VEP.

**Comment by magaliruffier** [comment]
fair enough
Will, do you think we will need to push the change to our servers or can it wait next time we update?

**Comment by willmclaren** [comment]
It can wait from main rest.ensembl.org's perspective

**Comment by magaliruffier** [comment]
The change has been ported to release/87 branch, @Zhicheng-Liu you should be good to use it for the EG server
Apologies for the delay

**Comment by Zhicheng-Liu** [comment]
@magaliruffier Great! Thank you for letting me know. I will update EG REST.

**Pull request merged**
