### PR TITLE
Several improvements for the Homology endpoints

### PR DESCRIPTION
**Pull request by muffato**
In short:
 - the Compara API is able to filter the target species
 - a few things could be rewritten in a clearer way

### CODE REVIEW

**Comment by magaliruffier** [comment]
that looks fine to me
Am I right in understanding that this does not affect the current behaviour of the endpoint, but makes the code behind it a bit more efficient?
Same caveat as for the other PRs, can we wait a few days before merging?

**Comment by muffato** [comment]
You're right: this is not a major version-number increase

**Comment by magaliruffier** [comment]
were you planning to get those changes in for release 83?

**Comment by muffato** [comment]
I think it's too late for that

**Comment by magaliruffier** [comment]
agreed, just making sure :-) Thanks for the changes either way!

**Pull request merged**
