### PR TITLE
Add new VEP plugin documentation 

### PR DESCRIPTION
**Pull request by dglemos**
### Description

One more VEP plugin will be available through the VEP endpoint. This documentation is needed for the plugin.

### Use case

Plugin functionality available through REST.

### Benefits

The endpoint needs documentation to be displayed.

### Possible Drawbacks

None, the default behavior is the same.

### Testing

_Have you added/modified unit tests to test the changes?_

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_
No regression detected.

### Changelog

_Are you changing the functionality of an endpoint? If so, please give a one line summary for the public facing changelog._

[/vep/:species/hgvs/] new plugin option added: DisGeNet
[/vep/:species/id/] new plugin option added: DisGeNet
[/vep/:species/region/] new plugin option added: DisGeNet

### CODE REVIEW

**Comment by ameya1981** [comment]
@dglemos Though the changes are only in the documentation, the test failures are because of variation test db not updated. Do you think you could raise a PR for 103 like the one for 102 (https://github.com/Ensembl/ensembl-rest/pull/435/files). All other PRs will be happy too! :)

**Comment by dglemos** [comment]
@ameya1981 We'll open a PR to update for 103.

**Comment by dglemos** [comment]
There was a type in DisGeNET, it's fixed now.

**Comment by ameya1981** [comment]
Good catch @bwalts. @dglemos you may want correct the url in https://github.com/Ensembl/ensembl-rest_private/pull/81/files too.

**Comment by dglemos** [comment]
@ameya1981 It's fixed

**Pull request merged**
