### PR TITLE
e91 regulation updates

### PR DESCRIPTION
**Pull request by juettemann**
Updated regulation tests/testdbs to deal with e91 updates to the funcgen repository.

### CODE REVIEW

**Comment by avullo** [comment]
Excellent, I'm here assuming you've run local tests and everything's fine.

P.S. When creating the PR, haven't you been presented with a template listing the requirements and sections with content to fill?

**Comment by lairdm** [comment]
Indeed, to echo Alessandro's comment, I'm not sure if this is a hickup with the new pull request template, but there's no description in the commit beyond "e91 regulation updates"

We have to be a little picky here, we really need a description/catalogue of the changes in the commit message for future debugging and change tracking. Thanks.

**Comment by juettemann** [comment]
Your wish is my command. Please let me know if you have more specific requirements what should go into the description.

**Comment by avullo** [comment]
Replace by a more recent and appropriate one.

**Pull request closed without merging**
