### PR TITLE
e89 Regulation updates

### PR DESCRIPTION
**Pull request by juettemann**

### CODE REVIEW

**Comment by magaliruffier** [comment]
the overlap test is still failing:
t/overlap.t ................. 40/? 
#   Failed test '/overlap/region/homo_sapiens/6:1020000..1030000?feature=chipseq | Getting probe_feature as JSON'
#   at /home/travis/build/Ensembl/ensembl-rest/t/lib/RestHelper.pm line 39.
# +----+------------------------------------------------------+----+------------------------------------------------------+
# | Elt|Got                                                   | Elt|Expected                                              |
# +----+------------------------------------------------------+----+------------------------------------------------------+
# |   0|[                                                     |   0|[                                                     |
# |   1|  {                                                   |   1|  {                                                   |
# |   2|    description => 'H3K27me3 - K562 enriched sites',  |   2|    description => 'H3K27me3 - K562 enriched sites',  |
# |   3|    end => 1024940,                                   |   3|    end => 1024940,                                   |
# |   4|    epigenome => 'K562',                              |   4|    epigenome => 'K562',                              |
# |   5|    feature_type => 'chipseq',                        |   5|    feature_type => 'chipseq',                        |
# *   6|    id => 10659628,                                   *    |                                                      |
# |   7|    score => '14.340487',                             |   6|    score => '14.340487',                             |
# |   8|    seq_region_name => 6,                             |   7|    seq_region_name => 6,                             |
# |   9|    source => 'ccat_histone',                         |   8|    source => 'ccat_histone',                         |
# |  10|    start => 1024000,                                 |   9|    start => 1024000,                                 |
# |  11|    strand => 0,                                      |  10|    strand => 0,                                      |
# |  12|    summit => 1024410                                 |  11|    summit => 1024410                                 |
# |  13|  }                                                   |  12|  }                                                   |
# |  14|]                                                     |  13|]                                                     |
# +----+------------------------------------------------------+----+------------------------------------------------------+
# Looks like you failed 1 test of 143.

**Comment by avullo** [comment]
You might wanna add the id field in the expected ref in the overlap unit test.

**Comment by juettemann** [comment]
It should not be there anymore, check the summary_as_hash here:
https://github.com/Ensembl/ensembl-funcgen/blob/master/modules/Bio/EnsEMBL/Funcgen/AnnotatedFeature.pm

I also don't get it when I run the test locally.

**Comment by magaliruffier** [comment]
The test suite is now passing successfully, after re-running it with the latest changes.
Next time, can you please ensure you have all changes in at the same time?
We've basically wasted time reviewing changes which were incomplete and this could have been avoided had you been more thorough.
Thanks

**Comment by juettemann** [comment]
I realised the problem before the first travis run was finished. I pushed them to master and asked Alessandro to kick it off again because I pushed an update to our repository. How long does it take travis to pick up such a change? I agree that I missed pushing out to ensembl-funcgen, but I let you guys know immediately and corrected it.

**Pull request merged**
