### PR TITLE
Phenotype endpoint updates -e101

### PR DESCRIPTION
**Pull request by ima23**
### Description

Adding 5 more option parameters to allow fetch of phenotype annotations subsets:  `trait`, `tumour`, `non_specified`.

### Use case

_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._

Currently all phenotype annotations are returned, however only some could be of interest. With these options only specific subsets of phenotypes will be retrieved. This reflects updates in how we store the data. 

### Benefits

Will be able to filter non specified phenotype annotations from the fetch result.

### Possible Drawbacks

None.

### Testing

_Have you added/modified unit tests to test the changes?_
Yes, I have added tests to cover the updates and updated the corresponding test data.

_If so, do the tests pass/fail?_
Yes, they pass.

_Have you run the entire test suite and no regression was detected?_
Yes, no regression detected.
Docs: http://hx-noah-12-02:3000/documentation/info/phenotype_gene
Tested [updated]: http://hx-noah-12-02:3000/phenotype/gene/homo_sapiens/LRRK2?content-type=application/json;include_associated=1;trait=1

### Changelog

_Are you changing the functionality of an endpoint? If so, please give a one line summary for the public facing changelog._

[/phenotype/gene/:species/:gene] new options added: trait, tumour, non_specified
[/phenotype/region/:species/:gene] new options added: trait, tumour, non_specified

### CODE REVIEW

**Comment by ima23** [comment]
@helensch : could you please also have a look at this PR? Thanks.

**Comment by helensch** [comment]
Looked at PR with @ima23 and it is fine.

**Comment by ima23** [comment]
Thanks for checking. After another thought I'll remove the `exclude` options. Testing now and will update this PR asap.

**Comment by ameya1981** [comment]
All tests have passed: https://travis-ci.org/github/Ensembl/ensembl-rest/builds/669217417

**Pull request merged**
