### PR TITLE
Extend the 'phenotypes' option in the Variation endpoint by adding th…

### PR DESCRIPTION
**Pull request by ens-lgil**
…e ontology accessions

### CODE REVIEW

**Comment by magaliruffier** [comment]
can we have some test cases please?
and for someone from variation to have a look why vep and ld are failing

**Comment by avullo** [comment]
Unfortunately, it's more than this, the overlap and regulatory tests have started to fail as well, something which was not happening on the latest master build, which is failing only ld and vep. The same happens on the PR 200 by @waakanni. Have they pull the latest changes from master?

**Comment by avullo** [comment]
Laurent, @waakanni forget about my last comment, this is not due to your changes, it's just a reminder for me of things to do (i.e. keep up to date)

**Comment by ens-lgil** [comment]
I just added a test. Thanks for the reminder!

**Comment by avullo** [comment]
thanks, let's wait travis

**Comment by magaliruffier** [comment]
travis is failing for unrelated reasons, PR should be fine

**Pull request merged**
