### PR TITLE
datafix: some rows were missing

### PR DESCRIPTION
**Pull request by muffato**
They should have been there in the first place. The compara API is now complaining on master

### CODE REVIEW

**Comment by lairdm** [comment]
Makes sense if the test data is needed.

**Comment by muffato** [comment]
Looks like cafe_tree.t also has an issue, I was only aware of cafe_tree.t. I'll have a look

**Comment by muffato** [comment]
OK, I've pushed more changes to compara master and restarted the Travis build. It now only fails for archive.t, see below
```
# +----+----------------------------------+----------------------------------+
# | Elt|Got                               |Expected                          |
# +----+----------------------------------+----------------------------------+
# |   0|{                                 |{                                 |
# |   1|  assembly => 'GRCh37',           |  assembly => 'GRCh37',           |
# |   2|  id => 'ENSG00000054598',        |  id => 'ENSG00000054598',        |
# |   3|  is_current => 1,                |  is_current => 1,                |
# |   4|  latest => 'ENSG00000054598.5',  |  latest => 'ENSG00000054598.5',  |
# |   5|  peptide => undef,               |  peptide => undef,               |
# |   6|  possible_replacement => [],     |  possible_replacement => [],     |
# *   7|  release => 88,                  |  release => 89,                  *
# |   8|  type => 'Gene',                 |  type => 'Gene',                 |
# |   9|  version => 5                    |  version => 5                    |
# |  10|}                                 |}                                 |
# +----+----------------------------------+----------------------------------+
```
I think it's not my fault ^^ but let me know if I can do anything. I can also rebase my PR if you push a fix to master

Matthieu

**Comment by muffato** [comment]
Any comment on this ? It's slightly inconvenient at the moment because our Travis build includes the REST test-suite and is failing because of the missing data

**Comment by muffato** [comment]
Have people had the chance to review this ?

**Comment by avullo** [comment]
Hi Matthieu, please bear with me I'm trying to reproduce the issue on my localhost but I'm having issues with the mysql version

**Comment by avullo** [comment]
I've patched the test DBs, no archive test error but got other ones related to the ld endpoint ...

**Comment by avullo** [comment]
Ok, we proceed with merging after patching, the errors I get from gene_tree.t should be taken into consideration by your changes, I guess.

**Comment by muffato** [comment]
Thank you @avullo. The ensembl-compara Travis build (incl. compara-related tests from ensembl-rest) now succeeds. I've checked the latest ensembl-rest Travis build and both ld.t and vep.t failed. My feeling is that it is unrelated to my PR, but let me know

**Comment by avullo** [comment]
It's more than a feeling ... ;)

**Pull request merged**
