### PR TITLE
Patch test databases for Release 110

### PR DESCRIPTION
**Pull request by nwillhoft**
### Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - the PR must not fail unit testing
    - if you're adding/updating documentation of an endpoint, make sure you add/update the necessary parameters to the (template) configuration files in the ensembl-rest_private repo

### Description

Updating test databases with patches for Release 110.

Current build check failures appear to be due to tests expecting 109 rather than 110.

Please note that 20 files are modified here, compared to 27 in the previous release (109, https://github.com/Ensembl/ensembl-rest/pull/553/files). However this appears to be fine because the `external_db.txt` files do no require modifying in this release.

### Use case

n/a

### Benefits

n/a

### Possible Drawbacks

n/a

### Testing

n/a

note to submitters and reviewers: documentation-only changes may reflect
changes in other repos that can result in new or different output from
REST endpoints. In turn, these may require new tests or changes to existing tests.

_Have you added/modified unit tests to test the changes?_

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_

### Changelog

_Are you changing the functionality of an endpoint? If so, please give a one line summary for the public facing changelog._

eg. [/xenobiology/orthologs] Added the ability to look up orthologs and paralogs from klingons and andorians

### CODE REVIEW

**Comment by nwillhoft** [comment]
@TamaraNaboulsi I can see that the patched SQL files contain these `ROW_FORMAT=DYNAMIC` (or `FIXED`) fields, which I remember you looked into and removed previously. Would you recommend doing this again here?

**Comment by TamaraNaboulsi** [comment]
> @TamaraNaboulsi I can see that the patched SQL files contain these `ROW_FORMAT=DYNAMIC` (or `FIXED`) fields, which I remember you looked into and removed previously. Would you recommend doing this again here?

The PR you're referring to is this one: https://github.com/Ensembl/ensembl/pull/646. There, I have kept the ROW_FORMAT changes, and an explanation is in the PR comments. Hope this helps!

**Comment by nwillhoft** [comment]
> > @TamaraNaboulsi I can see that the patched SQL files contain these `ROW_FORMAT=DYNAMIC` (or `FIXED`) fields, which I remember you looked into and removed previously. Would you recommend doing this again here?
> 
> The PR you're referring to is this one: [Ensembl/ensembl#646](https://github.com/Ensembl/ensembl/pull/646). There, I have kept the ROW_FORMAT changes, and an explanation is in the PR comments. Hope this helps!

Thanks Tamara, I had remembered that wrong, thanks for clarifying!

**Review by TamaraNaboulsi — CHANGES_REQUESTED** [review]
The tests suite is failing because it is still expecting version 109, which shouldn't happen. This is because the git clone version was hard-coded to release/109 in #553 . According to Stefano's comment there, it should have been reverted to main but that didn't happen. This needs to be fixed for the tests to work again.

**Comment by nwillhoft** [comment]
> The tests suite is failing because it is still expecting version 109, which shouldn't happen. This is because the git clone version was hard-coded to release/109 in #553 . According to Stefano's comment there, it should have been reverted to main but that didn't happen. This needs to be fixed for the tests to work again.

Thanks, this has been reverted back to `main` and the tests are in progress.

**Review by TamaraNaboulsi — APPROVED** [review]
Test DBs patched and test suite is succeeding. All looks good.

**Pull request merged**
