### PR TITLE
Add AlphaMissense plugin to VEP REST (e112)

### PR DESCRIPTION
**Pull request by nuno-agostinho**
### Description

Add AlphaMissense plugin to VEP REST ([ENSVAR-6262](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6262))

### Testing

Check documentation changes in my sandbox: http://hl-codon-36-01.ebi.ac.uk:3000/documentation/info/vep_region_get

### Changelog

[/vep] Added AlphaMissense plugin

### CODE REVIEW

**Review by jamie-m-a — APPROVED** [review]
Looks good - thanks Nuno

**Comment by nwillhoft** [comment]
Hi @nuno-agostinho, please could a duplicate PR also be made against the `main` branch. Thanks very much

**Comment by nuno-agostinho** [comment]
Hi @nwillhoft, done: https://github.com/Ensembl/ensembl-rest/pull/633. Thanks for your help!

**Review by nwillhoft — APPROVED** [review]
Approving this PR based on reviews from the Variation team, and changes look good. Build is passing.

**Pull request merged**
