### PR TITLE
Regulation 2024 updates (113)

### PR DESCRIPTION
**Pull request by pblins**
#### - Retire Regulation REST API endpoints ([ENSINT-1794](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-1794))

> Regulation has endpoints for retrieving regulatory feature activity and for listing epigenome metadata. 
> 
> [GET regulatory/species/:species/id/:id](https://rest.ensembl.org/documentation/info/regulatory_id)
> [GET regulatory/species/:species/epigenome](https://rest.ensembl.org/documentation/info/fetch_all_epigenomes)
> The schema for these is based on the Perl API, which is closely tied to the current site. However, we are developing new APIs for Ensembl beta, which will use the schema from our new pipeline and RDR (Regulation Data Registry).
> 
> As far as we can tell, these endpoints don’t seem heavily used. We would therefore like to retire them to avoid confusion. Users will be redirected to the beta site, the ftp site and/or the regulation subsite for up-to-date data.
> 
> For similar reasons, we will be removing the other_regulatory feature type from the overlap endpoints: [GET overlap/region/:species/:region](https://rest.ensembl.org/documentation/info/overlap_region) and [GET overlap/id/:id](https://rest.ensembl.org/documentation/info/overlap_id).

#### - Retire microarray REST API endpoints ([ENSINT-1776](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-1776))

> The Microarray probemapping pipeline has existed for a long time. It continues to run, but its maintenance and running costs outweigh the current importance of microarray technology and current usage numbers.  Regulation therefore intends to gradually phase out this pipeline. 
> 
> The microarray REST endpoints will be removed in 113:
> 
> [GET regulatory/species/:species/microarray/:microarray/vendor/:vendor](https://rest.ensembl.org/documentation/info/array)
> [GET regulatory/species/:species/microarray](https://rest.ensembl.org/documentation/info/list_all_microarrays)
> [GET regulatory/species/:species/microarray/:microarray/probe/:probe:](https://rest.ensembl.org/documentation/info/probe)
> [GET regulatory/species/:species/microarray/:microarray/probe_set/:probe_set](https://rest.ensembl.org/documentation/info/probe_set)

> For similar reasons, we will be removing the array_probe feature type from the overlap endpoints: [GET overlap/region/:species/:region](https://rest.ensembl.org/documentation/info/overlap_region) and [GET overlap/id/:id](https://rest.ensembl.org/documentation/info/overlap_id).

### Changelog

[GET regulatory/species/:species/id/:id](https://rest.ensembl.org/documentation/info/regulatory_id): ❌ removed 
[GET regulatory/species/:species/epigenome](https://rest.ensembl.org/documentation/info/fetch_all_epigenomes): ❌ removed
[GET regulatory/species/:species/microarray/:microarray/vendor/:vendor](https://rest.ensembl.org/documentation/info/array): ❌ removed 
[GET regulatory/species/:species/microarray](https://rest.ensembl.org/documentation/info/list_all_microarrays): ❌ removed 
[GET regulatory/species/:species/microarray/:microarray/probe/:probe:](https://rest.ensembl.org/documentation/info/probe): ❌ removed 
[GET regulatory/species/:species/microarray/:microarray/probe_set/:probe_set](https://rest.ensembl.org/documentation/info/probe_set): ❌ removed 
[GET overlap/region/:species/:region](https://rest.ensembl.org/documentation/info/overlap_region): ⚠️ updated (_other_regulatory_ and _array_probe_ removed as possible feature types)
[GET overlap/id/:id](https://rest.ensembl.org/documentation/info/overlap_id): ⚠️ update (_other_regulatory_ and _array_probe_ removed as possible feature types)

### CODE REVIEW

**Review by nwillhoft — COMMENTED** [review]
Build checks are failing due to version mismatch between 112 and 113, however this will be fixed once the latest PRs are merged in.

**Review by ilsley — APPROVED** [review]
I approve the scope of these changes.

**Review by daugo — APPROVED** [review]
The changes match the changelog description.

**Review by nwillhoft — APPROVED** [review]
PR approved by Regulation team and changes look good. Build checks are complaining about version mismatches but this is to be expected and will be fixed with an upcoming 113 patch PR.

**Pull request merged**
