### PR TITLE
Added a cpanfile

### PR DESCRIPTION
**Pull request by muffato**
which is basically a copy of Makefile.PL, but it simplifies setting-up a REST server on the user side and in other teams' test-suites

### CODE REVIEW

**Comment by magaliruffier** [comment]
fair enough, can't see any issue with this

**Comment by andrewyatz** [comment]
Only issue I can think is that we've got a duplication of dependencies in Makefile.PL and the cpanfile. Though the later of the two is more useful. Can the Makefile bring in the cpanfile?

Docs should be updated to reflect this as well

Andy

**Comment by muffato** [comment]
Done. Makefile.PL now loads the cpanfile

**Comment by magaliruffier** [comment]
cool, thanks ;-)

**Comment by andrewyatz** [comment]
Is that all that's needed to get a Makefile.PL to use a CPANfile to populate its dependency list? Just I've seen modules like http://search.cpan.org/~miyagawa/Module-Install-CPANfile-0.12/lib/Module/Install/CPANfile.pm that would suggest it's not as simple as a `do` statement. Perhaps I'm just being too worried

**Comment by magaliruffier** [comment]
I tested two empty VMS, one with cpan, the other with Makefile.PL, and seem to be getting to the same end result

**Comment by andrewyatz** [comment]
Ok that’s good. There are some explicit modules for this in the make module catalyst has chosen to use but I’m happy if it continues to build well :)

**Pull request merged**
