### PR TITLE
Accept transcript and translation IDs in the gene-tree endpoint

### PR DESCRIPTION
**Pull request by muffato**

### CODE REVIEW

**Comment by muffato** [comment]
RT #474615

**Comment by magaliruffier** [comment]
nice work, more extensive endpoints are always welcome

**Comment by nerdstrike** [comment]
Bonus points for some minimal tests? I guess we can merge it anyway.

**Comment by muffato** [comment]
Unfortunately, we're still missing a test-database for gene-trees and homologies

**Pull request merged**
