### PR TITLE
Tj1/probeset endpoint

### PR DESCRIPTION
**Pull request by juettemann**
New endpoint for probeset

### CODE REVIEW

**Comment by avullo** [comment]
Thanks Thomas.
We've patched the test DBs on master, including human funcgen, and a previously merged PR now makes the trascript haplotype test succeed. Unfortunately, this conflicts with your version of test funcgen schema.
Instead of resolving the conflict manually, would it be ok if we close this PR so that you open another one from the current master with:
- the probeset endpoint code/documentation;
- TESTS FOR THE PROBESET ENDPOINT (this is required if we want to accept);
- no commit about the startup script, if it's not making any changes.

**Comment by juettemann** [comment]
Sure, no problem. Could you advise how I get the startup script out of the commit?
Thanks!

**Comment by avullo** [comment]
I was more in favor of creating another PR on a different branch with no startup commit included. About removing commits, I don't if it's possible, but if it is my feeling is that it's complicated ;)

**Comment by magaliruffier** [comment]
It is easier to copy commits to a new branch than removing commits from an existing branch
Something like this should do the trick:
git checkout master
git pull
git branch feature/probeset_endpoint
git cherry-pick b3f944f198f85abc24
git cherry-pick 1e22de89433
git commit
git push

**Pull request closed without merging**
