### PR TITLE
Remove Gene Family REST endpoints

### PR DESCRIPTION
**Pull request by thiagogenez**
### Requirements

-  https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-5356

### Description

Compara gene and protein families were retired as of release 102, but three Family REST endpoints have remained. These should be removed as they are no longer reliably functional.

### Changelog

Ensembl 101 is the most recent release having a Compara database with Family data (see PR #528 ).

Consequently, all the `/family` endpoints are deprecated and removed from the REST service:

* `family/id/:id`
* `family/member/id/:id`
* `family/member/symbol/:species/:symbol`

### CODE REVIEW

**Review by TamaraNaboulsi — CHANGES_REQUESTED** [review]
The test **t/info.t** should be updated to handle this change. Line 237 is expecting 11 methods while they are now down to 10.

**Review by sgiorgetti — COMMENTED** [review]
@thiagogenez 

On top of @TamaraNaboulsi 's request for changes ... I would also change the PR description, especially RE "Changelog" section.

I would move the current contents in the "Description" section and replace the "Changelog" with the following. Please, let me know if you are happy with this.

### Changelog

Ensembl 101 is the most recent release having a Compara database with Family data (see PR #528 ).

Consequently, all the `/family` endpoints are deprecated and removed from the REST service:
- `family/id/:id`
- `family/member/id/:id`
- `family/member/symbol/:species/:symbol`

**Comment by thiagogenez** [comment]
> @thiagogenez
> 
> On top of @TamaraNaboulsi 's request for changes ... I would also change the PR description, especially RE "Changelog" section.
> 
> I would move the current contents in the "Description" section and replace the "Changelog" with the following. Please, let me know if you are happy with this.
> 
> ### Changelog
> Ensembl 101 is the most recent release having a Compara database with Family data (see PR #528 ).
> 
> Consequently, all the `/family` endpoints are deprecated and removed from the REST service:
> 
> * `family/id/:id`
> * `family/member/id/:id`
> * `family/member/symbol/:species/:symbol`

Thanks, @sgiorgetti for your feedback as well. Yes sure. I will address your recommendation.

**Review by TamaraNaboulsi — APPROVED** [review]
Change looks good. Tests are succeeding and changelog is updated accordingly.

**Pull request merged**
