### PR TITLE
Added 0 to frequency, count and allele_count to treat them as numeric…

### PR DESCRIPTION
**Pull request by premanand17**
… and to avoid getting returned as quoted text in results

### CODE REVIEW

**Comment by lairdm** [comment]
Makes sense. Yay loosely typed language.

**Comment by nerdstrike** [comment]
I suppose this ought to ideally be done further up the line, rather than us promoting the type in our context.

**Comment by nerdstrike** [comment]
We can just merge this and the travis error will go away on its own.

**Comment by lairdm** [comment]
Yup, Sarah has fixed the underlying issue

**Pull request merged**
