### PR TITLE
Compara endpoint update for grch37

### PR DESCRIPTION
**Pull request by carlacummins**
### Description

Updated compara endpoints to support removal of many species and analyses from GRCh37 REST service. This includes moving default values to the conf file (instead of hardcoding in the endpoint) and updating documentation & examples for GRCh37 purposes

### CODE REVIEW

**Comment by muffato** [comment]
Travis is now failing because the alignment endpoint is now returning unaligned sequences, and other output changes in the homology endpoints. If the default values have changed they need to be listed in order to be included in the Changelog and the test-suite needs to be updated. Otherwise, change the default values to what they were to preserve compatibility

**Comment by carlacummins** [comment]
@ameya1981 : which ensembl_rest.conf file is used by Travis? I didn't change the default values, I just moved them out to the config file.

**Comment by magaliruffier** [comment]
> @ameya1981 : which ensembl_rest.conf file is used by Travis? I didn't intend to change the default values, I just moved them out to the config file.

ensembl_rest_testing.conf, for example
https://github.com/Ensembl/ensembl-rest/blob/release/98/ensembl_rest_testing.conf

**Comment by carlacummins** [comment]
Failing tests are now in non-compara endpoints. Advice on how to proceed would be appreciated - should I try to fix them in this branch? (if yes, how?) Or are there fixes elsewhere that should be pulled into this branch? Thanks

**Pull request merged**
