### PR TITLE
Feature 84/ld increase window

### PR DESCRIPTION
**Pull request by at7**
We have worked on speed improvements for the LD calculation this release. We can now increase the window_size for the LD REST endpoint and make the window_size parameter customisable. Max allowed value is 1MB.

### CODE REVIEW

**Comment by nerdstrike** [comment]
Max value is 10^6 or 10^5?

**Comment by at7** [comment]
1 Mb

**Comment by nerdstrike** [comment]
1000/2 = 500 -> 500 * 100 = 50000. How many windows do you run? Also, I hope the called code can handle 499.5 in a window size.

**Comment by at7** [comment]
You specify the window size in kb: e.g. 25, 500, 1000. The code translates it into a number that's why * 100. 

Thanks for pointing out the division problem. Will add another test.

**Comment by at7** [comment]
Sorry, missing one zero here. I have to multiply by 1000.

**Comment by nerdstrike** [comment]
Not sure why the rate limit test is failing. That's not your fault.

**Pull request merged**
