### PR TITLE
eQTL endpoints deprecation

### PR DESCRIPTION
**Pull request by jcmarca**
### Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - the PR must not fail unit testing
    - if you're adding/updating documentation of an endpoint, make sure you add/update the necessary parameters to the (template) configuration files in the ensembl-rest_private repo

### Description

Deprecate the eQTL endpoints

### Use case

A new eQTL API is now developed by the eQTL Catalogue. The current eQTL endpoints in Ensembl REST is now deprecated.

### Benefits

Users will use the new eQTL API with extra functionality

### Possible Drawbacks

N/A

### Testing

It has been tested locally

_If so, do the tests pass/fail?_

It passes all tests

### Changelog
[eqtl/] "eQTL endpoints have been removed and replaced by the new eQTL catalogue API at https://www.ebi.ac.uk/eqtl/"

### CODE REVIEW

**Comment by ens-bwalts** [comment]
@jcmarca  - could you please provide the text that you would like to put in the changelog (https://github.com/Ensembl/ensembl-rest/wiki/Change-log) for this deprecation?

**Comment by jcmarca** [comment]
Yes, sorry. Changelog updated. Thank you

**Review by ens-bwalts — CHANGES_REQUESTED** [review]
It doesn't look like `t/test-genome-DBs/homo_sapiens/eqtl/homo_sapiens.hdf5` is used for any tests other than those in the now-deleted `eqtl.t`. If this is indeed the case, could you please delete that file from the test files.

**Comment by jcmarca** [comment]
Thanks for pointing this. All eQTL test DBs have been deleted now.

**Review by TamaraNaboulsi — APPROVED** [review]
eQTL endpoints are deprecated and thus removed from REST. The tests and dbs associated with eQTL were also removed and travis config updated accordingly. All checks pass and change looks good to me.

**Review by ens-bwalts — APPROVED** [review]
The eQTL endpoint, tests, and test supporting data are removed. Tests are passing

**Pull request merged**
