### PR TITLE
Enscoresw 1426

### PR DESCRIPTION
**Pull request by premanand17**

### CODE REVIEW

**Comment by magaliruffier** [comment]
the failures come from changes to the compara schema
if you rebase your branch against master, it should include the patches and pass successfully

**Comment by magaliruffier** [comment]
Can you also update the documentation please?
Probably this file:
https://github.com/Ensembl/ensembl-rest/blob/master/root/documentation/lookup.conf
with a boolean phenotypes option, similar to what is done for utr

**Comment by magaliruffier** [comment]
can you please rebase/merge against master?
test suite should be clean now

**Comment by nerdstrike** [comment]
Looks ok now

**Pull request merged**
