### PR TITLE
Update the Variation test, because of some changes in the Ensembl Var…

### PR DESCRIPTION
**Pull request by ens-lgil**
…iation API

### CODE REVIEW

**Comment by magaliruffier** [comment]
it is just the lower casing, isn't it?
can't see any problem with this, thanks for patching

**Comment by ens-lgil** [comment]
Actually it uses to be the "display term" (i.e. upper case and space in the examples) but the "SO term" should be the default term (i.e. lower case and under score in the examples).
We just changed the Ensembl Variation API to return the SO term by default.

**Comment by avullo** [comment]
Sorry, maybe it's just me but I fail to see the differences between the proposed and current version.

**Comment by ens-lgil** [comment]
The minor changes concern the "most_severe_consequence" attribute:
- First change: 'Intron variant' becomes 'intron_variant'
- Second change: 'Intergenic variant' becomes 'intergenic_variant'

**Comment by avullo** [comment]
Thanks Laurent, a coffee this morning was not enough :)

**Pull request merged**
