### PR TITLE
Update variation.conf

### PR DESCRIPTION
**Pull request by fcunningham**
changed variation to variant in the text

### CODE REVIEW

**Comment by magaliruffier** [comment]
if we want to be consistent, it probably needs to be changed for the other endpoints (VEP, GA4GH, overlap) as well as in the name space

**Comment by fcunningham** [comment]
Hi Mag,

Ahh good point!

For this page http://rest.ensembl.org/documentation/info/variation_id
Where can I edit this?

I think can leave the title as 'Variation' and the object name as
'variation' e.g. 'variation features'. (I know it isn't perfect).
I changed vep.conf and overlap too.

Fiona
-----------------------------------------------------------------
Fiona Cunningham, PhD
Variation Annotation Coordinator,
European Bioinformatics Institute (EMBL-EBI)
www.ensembl.org || www.lrg-sequence.org

**Comment by magaliruffier** [comment]
the variation.conf file should have all the mentions of variation from the http://rest.ensembl.org/documentation/info/variation_id page
https://github.com/fcunningham/ensembl-rest/blob/patch-1/root/documentation/variation.conf#L3
https://github.com/fcunningham/ensembl-rest/blob/patch-1/root/documentation/variation.conf#L13
...
unless you're talking about changing the url as well? I would rather avoid that if we can, as it would require all our users to update their scripts

**Comment by fcunningham** [comment]
Ok I think I did everything but let me know if you need more. No, no, no,
to changing the URLs ;o)

Fiona
-----------------------------------------------------------------
Fiona Cunningham, PhD
Variation Annotation Coordinator,
European Bioinformatics Institute (EMBL-EBI)
www.ensembl.org || www.lrg-sequence.org

**Comment by magaliruffier** [comment]
What about the example parameters?
id	String	Variation id	-	rs56116432
Do you want to change it to Variant id?
It's line 13 in this file
https://github.com/fcunningham/ensembl-rest/blob/patch-1/root/documentation/variation.conf#L13

**Comment by fcunningham** [comment]
Yes that would make sense. It just looked a bit like code and i was scared
I would break something. Do you want me to do it or will you?

Fiona
-----------------------------------------------------------------
Fiona Cunningham, PhD
Variation Annotation Coordinator,
European Bioinformatics Institute (EMBL-EBI)
www.ensembl.org || www.lrg-sequence.org

**Comment by magaliruffier** [comment]
if you can add this to this pull request, we can have all the changes in one place

**Comment by fcunningham** [comment]
Ok done.

Fiona
-----------------------------------------------------------------
Fiona Cunningham, PhD
Variation Annotation Coordinator,
European Bioinformatics Institute (EMBL-EBI)
www.ensembl.org || www.lrg-sequence.org

**Comment by magaliruffier** [comment]
looks good, thank your

**Pull request merged**
