### PR TITLE
At7/gwas/ld update

### PR DESCRIPTION
**Pull request by at7**
Reduce output for endpoint ld/id with attribs. Has been asked for by Ridwan for GWAS LD widget

### CODE REVIEW

**Comment by magaliruffier** [comment]
these fields are all new to this release, is that correct?
in other words, these changes are not on the current live endpoint?

**Comment by at7** [comment]
Correct. And they will only appear if used with attribs=1. This is foremost for the GWAS LD widget

**Comment by avullo** [comment]
Trying to understand here, does the reduced output preserve the amount of information returned?

**Comment by at7** [comment]
the endpoint receives an input variant and the computes pairwise LD stats for the input variant and all other variants in that region. because you know already everything about your input variant we only return attribs for the second variant. The use case is so far only the LD widget which joins the results of two endpoints. In order to avoid another REST call we put consequence and location information in the ld/id endpoint

**Comment by avullo** [comment]
Sounds sensible, thanks for the explanation.

**Pull request merged**
