### PR TITLE
Bme

### PR DESCRIPTION
**Pull request by ilavidas**
### Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - the PR must not fail unit testing
    - if you're adding/updating documentation of an endpoint, make sure you add/update the necessary parameters to the (template) configuration files in the ensembl-rest_private repo

### Description

_Using one or more sentences, describe in detail the proposed changes._
Add new BindingMatrix endpoint.
Update unit tests in order to comply with the updated release/94 branch of the ensembl-funcgen repo

### Use case

_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._

### Benefits

_If applicable, describe the advantages the changes will have._

### Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._

### Testing

_Have you added/modified unit tests to test the changes?_
Yes

_If so, do the tests pass/fail?_
Yes

_Have you run the entire test suite and no regression was detected?_
Yes

### Changelog

_Are you changing the functionality of an endpoint? If so, please give a one line summary for the public facing changelog._

eg. [/xenobiology/orthologs] Added the ability to look up orthologs and paralogs from klingons and andorians

### CODE REVIEW

**Comment by ilavidas** [comment]
I've pushed an additional commit which re-inserts whitespace. Should I create a new PR?

**Comment by ens-bwalts** [comment]
Either a new PR or amending/squashing your commits so that the whitespace changes don't show up, then re-pushing -- a new PR would probably be easier. The whitespace changes are still disrupting the commit history, which makes it harder to see when and why changes were put in and interferes with tools like git bisect.

**Comment by lairdm** [comment]
Can we close this pull request, @ilavidas? I see the "New" one.

**Comment by ilavidas** [comment]
Yes, please do

**Comment by lairdm** [comment]
You can close your own pull requests :)

**Comment by ilavidas** [comment]
I didn't know, thanks

**Pull request closed without merging**
