### PR TITLE
Add missing YAML CPAN dependency

### PR DESCRIPTION
**Pull request by nicklangridge**
Add missing YAML CPAN dependency as required here https://github.com/Ensembl/ensembl-rest/blame/release/97/lib/EnsEMBL/REST/Model/Documentation.pm#L33

### CODE REVIEW

**Comment by nerdstrike** [comment]
Odd. Does YAML::XS not imply YAML vanilla?

**Comment by mkszuba** [comment]
As far as I can tell from metacpan, not yet - the author plans to make YAML a front-end module for various implementations but for now it's just a specific, pure-Perl implementation - and a deprecated one to boot.

**Comment by nicklangridge** [comment]
Apparently not https://metacpan.org/pod/YAML::XS
> Dependencies
> none

I had to install it manually for the REST server this release. I'm not sure I've had to do it previously, but given that the YAML module is explicitly used I think it should be in cpanfile.

**Comment by nicklangridge** [comment]
I guess the use of YAML could be switched to YAML::XS but I'll leave that for you to decide.

**Comment by mkszuba** [comment]
@nicklangridge Just a quick reminder that there isn't much time left before the branching of release 98, if you would like to have this fixed by then.

**Comment by nicklangridge** [comment]
So you want a PR with YAML::XS in Documentation.pm instead of this solution?

**Comment by mkszuba** [comment]
Yes, if it works of course.

**Pull request merged**
