### PR TITLE
Patch test dbs to 108 / Update docs pointer to latest REST version

### PR DESCRIPTION
**Pull request by nwillhoft**
### Description

This PR contains 2 tasks:

1. Patch test databases in ensembl-rest repo to Release version 108

2. Update docs pointer to latest version (REST version 15.3, for Release 108). Refers to task A5 in the Infrastructure Release Tasks: https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=ENSCORE&title=Core+release+coordination#CoreReleaseCoordination-RESTserver-A5.

### Testing

note to submitters and reviewers: documentation-only changes may reflect
changes in other repos that can result in new or different output from
REST endpoints. In turn, these may require new tests or changes to existing tests.

_Have you added/modified unit tests to test the changes?_

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_

### Changelog

_Are you changing the functionality of an endpoint? If so, please give a one line summary for the public facing changelog._

eg. [/xenobiology/orthologs] Added the ability to look up orthologs and paralogs from klingons and andorians

### CODE REVIEW

**Comment by nwillhoft** [comment]
Have submitted my changes within the docs submodule by pushing onto another branch rather than master, but not sure how to create a PR for those separate changes.

**Comment by TamaraNaboulsi** [comment]
> Have submitted my changes within the docs submodule by pushing onto another branch rather than master, but not sure how to create a PR for those separate changes.

In the docs directory, you should push directly to `master` after you've added the changes. Once you do that and `cd ..` into the main ensembl-rest code, you can then `git add` the docs directory into your branch (update_docs_and_changes_for_108 in this case) and commit there

**Comment by nwillhoft** [comment]
> > Have submitted my changes within the docs submodule by pushing onto another branch rather than master, but not sure how to create a PR for those separate changes.
> 
> In the docs directory, you should push directly to `master` after you've added the changes. Once you do that and `cd ..` into the main ensembl-rest code, you can then `git add` the docs directory into your branch (update_docs_and_changes_for_108 in this case) and commit there

Thanks! Will get that done

**Review by TamaraNaboulsi — APPROVED** [review]
Docs version bumped to 15.3 and pointer updated. Also, test DBs were patched for 108.
I am wondering why `homo_sapiens/funcgen` DBs weren't updated though, since they were for 107 and ensembl-funcgen did branch for 108.
Other than that, all looks good to me.

**Review by sgiorgetti — CHANGES_REQUESTED** [review]
As @TamaraNaboulsi has mentioned, the Regulation (funcgen) DB is missing the bump to 108.
@nwillhoft would you mind to investigate it?

**Comment by nwillhoft** [comment]
> As @TamaraNaboulsi has mentioned, the Regulation (funcgen) DB is missing the bump to 108.
> @nwillhoft would you mind to investigate it?

Thanks, currently investigating this. Can see that the patch test databases script processed homo_sapiens/funcgen and identified that it needed patching to 108, however no action to patch the version was taken. Will investigate.

**Comment by nwillhoft** [comment]
Turns out I hadn't updated my ensembl-funcgen repo to contain the latest SQL patch file, so it wasn't picked up. The latest commit should hopefully fix this and contain the necessary patch data.

**Review by sgiorgetti — APPROVED** [review]

**Pull request merged**
