### PR TITLE
Update overlap/translation endpoint (release/113)

### PR DESCRIPTION
**Pull request by TamaraNaboulsi**
### Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - the PR must not fail unit testing
    - if you're adding/updating documentation of an endpoint, make sure you add/update the necessary parameters to the (template) configuration files in the ensembl-rest_private repo

### Description

Update behavior of `overlap/translation/:id` endpoint.

### Use case

A recent user query demonstrated that there is a difference in the description 

### Benefits

_If applicable, describe the advantages the changes will have._

### Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._

### Testing

note to submitters and reviewers: documentation-only changes may reflect
changes in other repos that can result in new or different output from
REST endpoints. In turn, these may require new tests or changes to existing tests.

_Have you added/modified unit tests to test the changes?_

2 subtests were added into the overlap.t test, as well as an update in info.t to handle the extra xref added.

_If so, do the tests pass/fail?_

Tests are succeeding.

_Have you run the entire test suite and no regression was detected?_

Yes.

### Changelog

_Are you changing the functionality of an endpoint? If so, please give a one line summary for the public facing changelog._

[overlap/translation/:id] Use protein feature description if no Interpro xref exists.

### CODE REVIEW

**Review by sgiorgetti — APPROVED** [review]
OK

**Review by sgiorgetti — CHANGES_REQUESTED** [review]
realised the build is failing for PR. Better check what's going on

**Comment by TamaraNaboulsi** [comment]
> realised the build is failing for PR. Better check what's going on

This seems to be happening because the ensembl-vep repo hasn't branched for 113 yet

**Review by sgiorgetti — APPROVED** [review]
Confirmed. All good!

**Pull request merged**
