### PR TITLE
Return structural variants by ID in Variation/VEP endpoints

### PR DESCRIPTION
**Pull request by nuno-agostinho**
### Description

[ENSVAR-5793](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5793): Return structural variants (SVs) by their ID when using Variation/VEP endpoints.

The information displayed for SVs is based on their Ensembl Variation page: for instance, [esv1815690](https://www.ensembl.org/Homo_sapiens/StructuralVariation/Mappings?db=core;sv=esv1815690)

Requires https://github.com/Ensembl/ensembl-variation/pull/1029.

### Use case

Users request that these endpoints return SVs (e.g., `esv1815690`). Currently, they only return non-SVs (e.g., `rs699`).

### Possible Drawbacks

If all IDs are non-SVs, the code will take the same time as before; otherwise, the code looks for the mismatched IDs in the SV table.

Also, some SVs may hit the memory limit, such as in the case of `nsv3901821`, and return an error message: `ERROR: Cannot allocate memory`.

### Testing

Unit tests added (but failing because they require https://github.com/Ensembl/ensembl-variation/pull/1029).

#### Some examples

- http://wp-np2-11.ebi.ac.uk:9300/vep/human/id/esv1815690
- http://wp-np2-11.ebi.ac.uk:9300/variation/human/esv1815690
```bash
# POST variation/human
curl -d '{ "ids" : ["esv1815690", "rs699", "cnvi0111251"] }' -H "Content-Type: application/json" http://wp-np2-11.ebi.ac.uk:9300/variation/human

# POST vep/human/id
curl -d '{ "ids" : ["esv1815690", "rs699", "cnvi0111251"] }' -H "Content-Type: application/json" http://wp-np2-11.ebi.ac.uk:9300/vep/human/id
```

#### Documentation changes

Check the following documentation updates in my sandbox:
- http://wp-np2-11.ebi.ac.uk:9300/documentation/info/variation_id
- http://wp-np2-11.ebi.ac.uk:9300/documentation/info/variation_post
- http://wp-np2-11.ebi.ac.uk:9300/documentation/info/vep_id_get
- http://wp-np2-11.ebi.ac.uk:9300/documentation/info/vep_id_post

### Changelog

[/variation/:species/id] Return structural variants by their ID
[/variation/:species] Return structural variants by their ID
[/vep/:species/id] Return structural variants by their ID
[/vep/:species] Return structural variants by their ID

### CODE REVIEW

**Comment by dglemos** [comment]
The documentation specifies which type of ID is supported: http://rest.ensembl.org/documentation/info/vep_id_get
Maybe you could update the docs to make it clear SV IDs are also supported.

**Comment by nuno-agostinho** [comment]
Hey @dglemos, opened this PR to document the changes to REST: https://github.com/Ensembl/ensembl-rest/pull/604

**Comment by nwillhoft** [comment]
Hi @nuno-agostinho, please could I check if this is for Release 111 or 112? Thanks!

**Comment by nuno-agostinho** [comment]
Hi @nwillhoft, this is for 112, so need to rush. Still waiting for an approval from @dglemos. Thanks for asking!

**Review by dglemos — APPROVED** [review]

**Review by nwillhoft — APPROVED** [review]
Approving PR based on code review carried out by Variation team.

**Pull request merged**
