### PR TITLE
At7/postrelease84/ld windowsize

### PR DESCRIPTION
**Pull request by at7**
I've changed the default window size to 500 KB. That is still very generous compared to what we use as default on the website. But I hope it will prevent death by LD. I'lll continue looking into how we can speed up the computations.

### CODE REVIEW

**Comment by nerdstrike** [comment]
Thanks Anja, Magali has noticed a significant decline in performance versus our test server from release 83. Did a lot change between releases?

**Comment by at7** [comment]
We changed the window size from 50 KB to 1000 KB. We were confident that our speed improvements could deal with this.

**Comment by magaliruffier** [comment]
we're now down to about half the time, 16 seconds rather than 35
If this going to be enough?
btw, the test suite is failing because of the changes to htslib and the like
can you also submit the PR against master where we can check against regressions?

**Comment by at7** [comment]
Can you try any of the requests Kieron has sent me?

/ld/Human/rs1094732?content-type=application/json;population_name=1000GENOMES:phase_3:GBR;r2=0.500000

/ld/Human/rs9302874?content-type=application/json;population_name=1000GENOMES:phase_3:GBR;r2=0.500000

**Comment by magaliruffier** [comment]
the first example one times out on the live server
with the fix, it returns in about 24 seconds
the second example returns in 46 seconds (just misses the time out)
with the fix, results come back in about 21 seconds

**Comment by at7** [comment]
That is much better.

**Comment by magaliruffier** [comment]
ok, if you think those times are reasonable, we can accept the PR and push the changes to the live servers

**Comment by at7** [comment]
yes that's fine. thank you

**Pull request merged**
