### PR TITLE
Add AncestralAllele docs

### PR DESCRIPTION
**Pull request by nuno-agostinho**
### Description

The VEP endpoint uses the external plugin AncestralAllele that is already available in REST. This documentation is needed for the plugin. @dglemos

### Use case

Documentation of VEP plugin available through REST.

### Benefits

The endpoint needs documentation to be displayed.

### Possible Drawbacks

None, the default behavior is the same.

### Testing

Tested by running [ensembl_rest_server.pl](https://github.com/Ensembl/ensembl-rest/blob/release/105/script/ensembl_rest_server.pl). Documentation shows as expected.

### Changelog

[/vep/:species/hgvs/] plugin option available: AncestralAllele
[/vep/:species/id/] plugin option available: AncestralAllele
[/vep/:species/region/] plugin option available: AncestralAllele

### CODE REVIEW

**Comment by nuno-agostinho** [comment]
Sorry, forgot to mention: this is meant for release 107. Thanks!

**Comment by TamaraNaboulsi** [comment]
Hi @nuno-agostinho. We need the changelog for this PR to be stated as described in the example. Looking at the previous PRs similar to this one, am I right to assume that the changelog for this is the following? Please confirm.

[/vep/:species/hgvs/] new plugin option added: AncestralAllele
[/vep/:species/id/] new plugin option added: AncestralAllele
[/vep/:species/region/] new plugin option added: AncestralAllele

**Comment by nuno-agostinho** [comment]
Hi @TamaraNaboulsi, exactly, that is the proper changelog.

**Comment by dglemos** [comment]
Hi @TamaraNaboulsi, this plugin has been available for a while in VEP, we are just adding the missing docs. 
Could we add something like this:
[/vep/:species/hgvs/] plugin option available: AncestralAllele
[/vep/:species/id/] plugin option available: AncestralAllele
[/vep/:species/region/] plugin option available: AncestralAllele

**Review by dglemos — APPROVED** [review]

**Comment by TamaraNaboulsi** [comment]
> Hi @TamaraNaboulsi, this plugin has been available for a while in VEP, we are just adding the missing docs. Could we add something like this: [/vep/:species/hgvs/] plugin option available: AncestralAllele [/vep/:species/id/] plugin option available: AncestralAllele [/vep/:species/region/] plugin option available: AncestralAllele

Hi @dglemos, yes the changelog can be whatever you need it to be. I just copy it when I perform the repo branching. I will use what you stated instead.

**Comment by dglemos** [comment]
Thanks! We will update it then.

**Pull request merged**
