### PR TITLE
Revert behaviour of old Compara endpoints

### PR DESCRIPTION
**Pull request by twalsh-ebi**
### Description

[Ensembl REST PR #583](https://github.com/Ensembl/ensembl-rest/pull/583) deprecated Compara REST endpoints supporting queries by gene/sequence object stable ID, and introduced replacement endpoints supporting queries by species name and object stable ID.

In PR #583 and the follow-up [PR #587](https://github.com/Ensembl/ensembl-rest/pull/587), the deprecated endpoints were coded to try to catch duplicate stable IDs. However, the approach taken was not performant, so this PR completely reverts endpoints `[/cafe/genetree/member/id/:id]` and `[/genetree/member/id/:id]` to be consistent with their previous behaviour, and partially reverts the behaviour of `[/homology/id/:id]`.

In addition, unit tests of handling of stable ID clashes have been removed.

**NB**: [Ensembl REST PR #594](https://github.com/Ensembl/ensembl-rest/pull/594) applied these changes to the `release/110` branch, and this PR replicates those changes on the `main` branch.

### Use case

This PR addresses performance issues with updates to the 3 deprecated Compara REST endpoints.

### Benefits

The deprecated Compara endpoints are more performant.

### Possible Drawbacks

Not all member stable ID clashes will raise an error. However, this is not a disimprovement on the previous behaviour of the affected endpoints.

### Testing

All Compara unit tests pass locally, whether with or without the `multi/stable_ids` test database.

### Notes

No PR has been submitted to `ensembl-rest_private`, as no changes have been made to the documentation.

### CODE REVIEW

**Review by thiagogenez — APPROVED** [review]
Looks good for me. 

Just a reminder that the Travis errors are related to version mismatches between the software and DB versions. They are unrelated to the PR itself.

**Comment by nwillhoft** [comment]
@twalsh-ebi would anything need adding to the change log relating to this PR? Thanks

**Comment by twalsh-ebi** [comment]
> @twalsh-ebi would anything need adding to the change log relating to this PR? Thanks

Thanks for merging this PR @nwillhoft.

I believe there isn't anything for the changelog in this PR as it reverts aspects of the relevant Compara endpoint behaviour to how it was previously. That said, there were some changelog updates in PR #583 ([here](https://github.com/Ensembl/ensembl-rest/pull/583#user-content-pr583-changelog)) which may be relevant.

**Comment by nwillhoft** [comment]
> > @twalsh-ebi would anything need adding to the change log relating to this PR? Thanks
> 
> Thanks for merging this PR @nwillhoft.
> 
> I believe there isn't anything for the changelog in this PR as it reverts aspects of the relevant Compara endpoint behaviour to how it was previously. That said, there were some changelog updates in PR #583 ([here](https://github.com/Ensembl/ensembl-rest/pull/583#user-content-pr583-changelog)) which may be relevant.

Thanks @twalsh-ebi. I had previously added the following text to the change log, and then removed it when the PR revert happened. Would it now be appropriate to add this back into the change log?

```
[/cafe/genetree/member/id/:id] is deprecated and replaced by [/cafe/genetree/member/id/:species/:id]
[/genetree/member/id/:id] is deprecated and replaced by [/genetree/member/id/:species/:id]
[/homology/id/:id] is deprecated and replaced by [/homology/id/:species/:id] 
```

**Comment by twalsh-ebi** [comment]
> > > @twalsh-ebi would anything need adding to the change log relating to this PR? Thanks
> > 
> > 
> > Thanks for merging this PR @nwillhoft.
> > I believe there isn't anything for the changelog in this PR as it reverts aspects of the relevant Compara endpoint behaviour to how it was previously. That said, there were some changelog updates in PR #583 ([here](https://github.com/Ensembl/ensembl-rest/pull/583#user-content-pr583-changelog)) which may be relevant.
> 
> Thanks @twalsh-ebi. I had previously added the following text to the change log, and then removed it when the PR revert happened. Would it now be appropriate to add this back into the change log?
> 
> ```
> [/cafe/genetree/member/id/:id] is deprecated and replaced by [/cafe/genetree/member/id/:species/:id]
> [/genetree/member/id/:id] is deprecated and replaced by [/genetree/member/id/:species/:id]
> [/homology/id/:id] is deprecated and replaced by [/homology/id/:species/:id] 
> ```

Yes please @nwillhoft, that would be great. 🙂 The reversion mainly affected the behaviour of the old endpoints, and the new endpoints will still be replacing them.

**Pull request merged**
