### PR TITLE
Removing documentation spliceregion rest

### PR DESCRIPTION
**Pull request by olaaustine**
## Description
Removing SpliceRegion VEP plugin from ensembl rest. As Splice region consequences is calculated by VEP by default
[ENSVAR-4922](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4922)

### CODE REVIEW

**Comment by olaaustine** [comment]
@dglemos, please can you check this PR ?

**Comment by olaaustine** [comment]
@dglemos, please can you check this PR?
Thank you

**Review by dglemos — APPROVED** [review]
Looks good!

**Review by sgiorgetti — APPROVED** [review]
Removal of SpliceRegion VEP plugin.
Looks good

**Pull request merged**
