### PR TITLE
Several improvements to the Gene-tree endpoints

### PR DESCRIPTION
**Pull request by muffato**
In short:
 - added options to prune the gene-trees (like on the homology side)
 - added more examples

### CODE REVIEW

**Comment by magaliruffier** [comment]
can I have some basic tests for it as well?
If I understand correctly, this will not affect existing output but allows for two new options, is that right?
we'll declare these for release 84 and add a minor version increment

**Comment by muffato** [comment]
Tests ... Perhaps in e84 ? That's the reason why this PR and #95 have been pending for a couple of releases. I was hoping to find a way of making a Compara DB but I haven't yet

**Comment by magaliruffier** [comment]
I take it the test database we have does not cover enough cases?

**Comment by muffato** [comment]
There is nothing related to gene-trees / homologies in this test-db

**Comment by magaliruffier** [comment]
I can see that being a problem

**Comment by muffato** [comment]
It is, I know

**Pull request merged**
