### PR TITLE
Compara test db homologies

### PR DESCRIPTION
**Pull request by muffato**
Habemus testis !

I have added a test database that can cover gene-trees and homologies. Currently, only the /homology/id/ endpoint is tested but I will add the other ones soon.
At the same time, I fixed a couple of bugs

### CODE REVIEW

**Comment by nerdstrike** [comment]
Looks useful. Approved

**Comment by nerdstrike** [comment]
Urk. DBD::mysql::db do failed: Specified key was too long; max key length is 1000 bytes

Suggests a missing character set assignment.

**Comment by muffato** [comment]
The charset is defined in my original database, but is missing from the database dump. Is it stripped out by dump_mysql.pl ?

**Comment by muffato** [comment]
Indeed the charset definition is removed when --testcompatible is given, which I used (following https://www.ebi.ac.uk/seqdb/confluence/display/ENSCORE/Creating+a+test+database)

**Comment by nerdstrike** [comment]
It wouldn't come up if people didn't have massive keys. I suppose we'll have to change our guide.

**Comment by muffato** [comment]
I think the problem comes from our meta table.
```sql
CREATE TABLE IF NOT EXISTS meta (

  meta_id                     INT NOT NULL AUTO_INCREMENT,
  species_id                  INT UNSIGNED DEFAULT 1,
  meta_key                    VARCHAR(40) NOT NULL,
  meta_value                  TEXT NOT NULL,

  PRIMARY   KEY (meta_id),
  UNIQUE    KEY species_key_value_idx (species_id, meta_key, meta_value(255)),
            KEY species_value_idx (species_id, meta_value(255))

);
```
It's different from what you guys have in the core schema
```sql
CREATE TABLE IF NOT EXISTS meta (

  meta_id                     INT NOT NULL AUTO_INCREMENT,
  species_id                  INT UNSIGNED DEFAULT 1,
  meta_key                    VARCHAR(40) NOT NULL,
  meta_value                  VARCHAR(255) BINARY,

  PRIMARY   KEY (meta_id),
  UNIQUE    KEY species_key_value_idx (species_id, meta_key, meta_value),
            KEY species_value_idx (species_id, meta_value)

);
```

**Comment by muffato** [comment]
Didn't work ... I'll try to reproduce this locally to identify the offending keys (rather than blindly adding a charset everywhere)

**Comment by magaliruffier** [comment]
external_db is a good candidate
UNIQUE KEY `db_name_db_release_idx` (`db_name`,`db_release`)
with
`db_name` varchar(100) NOT NULL,
 `db_release` varchar(255) DEFAULT NULL,

**Comment by magaliruffier** [comment]
but otherwise, thanks for the tests, it looks promising 👍

**Comment by muffato** [comment]
Yeah ! Thank you @magaliruffier for the tip !

**Pull request merged**
