### PR TITLE
Adding changes for Enformer

### PR DESCRIPTION
**Pull request by olaaustine**
[ENSVAR-5917](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5917)

Possible Drawbacks
No drawbacks.

Testing
Changes to documentation can be checked in http://wp-np2-11.ebi.ac.uk:7075/documentation/info/vep_region_get

Changelog
[/vep] Documented Enformer plugin

### CODE REVIEW

**Review by nuno-agostinho — CHANGES_REQUESTED** [review]
Hi @olaaustine, can you change the description to match what was decided on https://github.com/Ensembl/VEP_plugins/pull/618?

`Predictions of variant impact on gene expression`

Thanks!

**Comment by olaaustine** [comment]
> Hi @olaaustine, can you change the description to match what was decided on [Ensembl/VEP_plugins#618](https://github.com/Ensembl/VEP_plugins/pull/618)?
> 
> `Predictions of variant impact on gene expression`
> 
> Thanks!

Done. Thank you!

**Review by nuno-agostinho — APPROVED** [review]
Looks good to me, thanks @olaaustine!

**Comment by nwillhoft** [comment]
Hi @olaaustine, please could I check if this is for Release 111 or 112? Thanks!

**Comment by olaaustine** [comment]
Hi @nwillhoft, 
Please is it possible to go in for release 111.
Thank you

**Comment by nwillhoft** [comment]
> Hi @nwillhoft,
> Please is it possible to go in for release 111.
> Thank you

Hi @olaaustine, no problem to get this into Release 111. Please could you create a duplicate PR to also push these changes against the `release/111` branch? Thanks a lot

**Review by nwillhoft — APPROVED** [review]
Code changes look good for adding in Enformer-related documentation. PR has been approved by Variation team and build checks are passing.

**Pull request merged**
